const cityNames = ['Mariehamn','Jomala','Finström','Lemland','Saltvik','Hammarland','Sund','Eckero','Foglo',
'Brando','Geta','vardo','Kumlinge','Kokar','Tirana','Durres','Elbasan','Vlore','Shkoder','Korce',
'Fier','Berat','Lushnje','Kavaje','Lac','Gjirokaster','Patos Fshat','Kruje','Lezhe','Kucove','Kukes',
'Burrel','Sarande','Peshkopi','Cerrik','Shijak','Corovode','Librazhd-Qender','Tepelene','Gramsh',
'Bulqize','Kamez','Permet','Andorra la Vella','les Escaldes','Encamp','Sant Julia de Loria','la Massana',
'Canillo','Ordino','Pas de la Casa','Arinsal','El Tarter','Vienna','Graz','Linz','Salzburg','Innsbruck',	
'Klagenfurt am Worthersee','Villach','Wels','Sankt Polten','Dornbirn','Steyr','Wiener Neustadt','Feldkirch',
'Bregenz','Wolfsberg','Baden','Klosterneuburg','Leoben','Traun','Kapfenberg','Lustenau','Hallein Salzburg',
'Spittal an der Drau','Eisenstadt','Minsk','Gomel','Mahilyow','Vitebsk','Brest','Hrodna','Babruysk','Baranovichi',
'Pinsk','Novoye Medvezhino','Orsha','Mazyr','Lida','Salihorsk','Maladzyechna','Navapolatsk','Polatsk','Zhlobin',
'Svyetlahorsk','Slonim','Kobryn','Vawkavysk','Brussels','Antwerpen','Gent','Charleroi','Liege','Brugge','Namur',
'Leuven','Mons','Aalst','Mechelen','La Louviere','Sarajevo','Banja Luka','Zenica','Tuzla','Mostar','Bihac','Bugojno',
'Brcko','Bijeljina','Prijedor','Trebinje','Sofia','Plovdiv','Varna','Burgas','Ruse','Stara Zagora','Pleven','Sliven',
'Dobrich','Shumen','Pernik','Yambol','Haskovo',	'Pazardzhik','Blagoevgrad','Veliko Turnovo','Gabrovo','Vratsa','Kazanluk',
'Vidin','Kurdzhali','Kyustendil','Montana','Lovech','Silistra','Razgrad','Targovishte','Smolyan','Elin Pelin','Zagreb',
'Split','Rijeka','Osijek','Zadar','Slavonski Brod','Pula','Sesvete','Karlovac','Varazdin','Stenjevec','Sibenik',
'Sisak','Velika Gorica','Vinkovci','Vukovar','Dubrovnik','Bjelovar','Koprivnica','Pozega','Zapresic','Solin',
'Cakovec','Virovitica','Samobor','Kutina','Gospic','Pazin','Krapina','Prague','Brno','Ostrava','Stary Plzenec',
'Pilsen','Liberec','Olomouc','Ceske Budejovice','Usti nad Labem','Hradec Kralove','Pardubice','Havirov','Zlin',
'Kladno','Most','Karvina','Opava','Decin','Karlovy Vary','Teplice','Jihlava','Prostejov','Prerov',
'Jablonec nad Nisou','Mladá Boleslav','Ceska Lipa','Trebic','Copenhagen','Arhus','Aalborg','Odense','Esbjerg',
'Vejle','Frederiksberg','Randers','Kolding','Horsens','Hvidovre','Greve','Herning','Roskilde','Silkeborg',
'Næstved','Ballerup','Viborg','Koge','Hillerod','Soro','Tallinn','Tartu','Narva','Kohtla-Jarve','Parnu',
'Viljandi','Rakvere','Sillamae','Maardu','Kuressaare','Voru','Valga','Haapsalu','Johvi','Paide','Keila',
'Tapa','Polva','Jogeva','Turi','Elva','Rapla','Saue','Poltsamaa','Kardla','Torshavn','Klaksvik','Hoyvik',
'Argir','Vagur','Fuglafjorour','Vestmanna','Tvoroyri','Sorvagur','Kollafjorour','Miovagur','Eioi',
'Sandur','Helsinki','Espoo','Tampere','Vantaa','Oulu','Turku','Jyvaskyla','Lahti','Kuopio','Pori',
'Lappeenranta','Vaasa','Joensuu','Hameenlinna','Porvoo','Mikkeli','Kokkola','Kajaani','Rovaniemi',
'Seinajoki','Paris','Marseille','Lyon','Toulouse','Nice','Nantes','Montpellier','Strasbourg',
'Bordeaux','Lille','Rennes','Reims','Cergy-Pontoise','Le Havre','Saint-Etienne','Toulon',
'Dijon','Clermont-Ferrand','Limoges','Amiens','Metz','Besancon','Orleans','Rouen','Caen','Nanterre',
'Poitiers','Ajaccio','Châlons-en-Champagne','Berlin','Hamburg','Munich','Cologne','Frankfurt am Main',
'Stuttgart','Dusseldorf','Leipzig','Dortmund','Essen','Bremen','Dresden','Hannover','Nuremberg','Duisburg',
'Karlsruhe','Wiesbaden','Kiel','Magdeburg','Mainz','Erfurt','Saarbrucken','Potsdam','Schwerin','Athens',
'Thessaloniki','Patra','Piraeus','Peristeri','Irakleion','Larisa','Kallithea','Acharnes','Kalamaria','Nikaia',
'Volos','Ioannina','Lamia','Komotini','Kozani','Mytilini','Kerkyra','Tripoli','Ermoupolis','Guernsey','Budapest',
'Debrecen','Szeged','Miskolc','Pecs','Gyor','Nyiregyhaza','Kecskemet','Szekesfehervar','Szombathely',
'Paradsasvar','Szolnok','Tatabanya','Kaposvar','Bekescsaba','Erd','Veszprem','Zalaegerszeg','Eger','Dunaujvaros',
'Hodmezovasarhely','Salgotarjan','Cegled','Vac','Szekszard','Reykjavik','Kopavogur','Hafnarfjorour','Akureyri',
'Garoabar','Mosfellsbar','Akranes',	'Selfoss','Seltjarnarnes','Vestmannaeyjar','Grindavik','Isafjorour',
'Sauoarkrokur','Egilsstaoir','Hverageroi','Egilsstaoir','Husavik','Reykjanesbar','Borgarnes','Hofn','Sandgeroi',
'Þorlakshofn','Neskaupstaour','Garour','Dalvik','Siglufjorour','Stykkisholmur','Dublin','Dun Laoghaire','Cork',
'Luimneach','Gaillimh','Tallaght','Waterford','Swords','Drogheda','Dundalk','Navan','Ennis','Tralee','Sligo',
'Letterkenny','Cavan','Nenagh','Douglas','Ramsey','Peel','Port Erin','Castletown','Laxe','Rome','Milano',
'Napoli','Turin','Palermo','Genoa','Bologna','Florence','Bari','Catania','Verona','Messina','Padova',
'Trieste','Taranto','Brescia','Parma','Prato','erugia','Cagliari','Latina','Trento','Ancona','Catanzaro',
'Potenza','Venice','Campobasso','LAquila','Aosta','Jersey','Moscow','Saint Petersburg','Novosibirsk',
'Yekaterinburg','Nizhniy','Kazan','Samara','Omsk','Chelyabinsk','Rostov-na-Donu','Ufa','Krasnoyarsk',
'Perm','Volgograd','Voronezh','Saratov','Krasnodar','Izhevsk','Barnaul','Tyumen','Ulyanovsk','Irkutsk',
'Vladivostok','Yaroslavl','Khabarovsk','Makhachkala','Orenburg','Madrid','Barcelona','Valencia',
'Sevilla','Zaragoza','Malaga','Murcia','Palma','Las Palmas','Bilbao','Alicante','Cordoba',
'Valladolid','Vigo','Gijon','L’Hospitalet de Llobregat','A Coruna','Gasteiz','Granada',
'Oviedo','Mostoles','Pamplona','Santander','Logrono','Santiago','Toledo','Ceuta','Melilla',
'Merida','Mexico City','Puebla','Guadalajara','Monterrey','Chihuahua','Merida',
'Aguascalientes','Saltillo','Mexicali','San Luis Potosi','Culiacan','Hermosillo',
'Santiago de Queretaro','Morelia','Tuxtla Gutierrez','Toluca','Xalapa de Enriquez',
'Villahermosa','Cuernavaca','Tepic','Ciudad Victoria','Pachuca de Soto',
'Oaxaca de Juare','La Paz','Campeche','Chilpancingo de los Bravos','Colima'
,'Chetumal','Zacatecas','Tlaxcala de Xicohtencatl','Manama','Al Muharraq','Ar Rifa',
'Dar Kulayb','Madinat Hamad','Madinat ’Isa','Sitrah','Jidd Hafs','Al Hadd','Baghdad',
'Al Basrah','Abu Ghurayb','Erbil','As Sulaymaniyah','Mosul','Kirkuk','An Najaf','Karbala',
'An Nasiriyah','Al ’Amarah','Ad Diwaniyah','Al Kut','Al Hilla','Dihok','Ramadi','Al Fallujah',
'Samarra','As Samawah','Baqubah','Sinah','Az Zubayr','Kufa','Umm Qasr','Al Faw','Zaxo','Ash Shatrah',
'Al Hayy','Tikrit','Cairo','Alexandria','Giza','Port Said','Suez','Al Mahallah al Kubra','Luxor',
'Asyut','Al Mansurah','Tanda','Al Fayyum','Zagazig','Ismailia','Kafr ad Dawwar','Aswan','Qina','Damanhur'
,'Al Minya','Damietta','Sohag','Bani Suwayf','Shibin al Kawm','Banha','Kafr ash Shaykh','Arish','Hurghada',
'Al Kharijah','Mersa Matruh','El-Tor','Tunis','Sfax','Sousse','Midoun','Kairouan','Bizerte','Gabes',
'Ariana','Kasserine','Gafsa','La Goulette','Zarzis','Ben Arous','Monastir','La Mohammedia','Al Marsa',
'Tataouine','Medenine','Beja','Nabeul','Jendouba','El Kef','Mahdia','Sidi Bouzid','Tozeur','Siliana',
'Manouba','Kebili','Zaghouan','Abu Dhabi','Dubai','Sharjah','Al Ain','Ajman','Ras al-Khaimah','Al Fujayrah'
,'Umm al Qaywayn','Khawr Fakkan','Dibba Al-Fujairah','Dibba Al-Hisn','Adh Dhayd','Ar Ruways','Muzayri',
'Riyadh','Jeddah','Mecca','Medina','Dammam','Al Hufuf','Ta’if','Tabuk','Buraydah','Khamis Mushait','Al Jubayl'
,'Najran','Al Mubarraz','Hayil','Abha','Yanbu al Bahr','‘Ar‘ar','Unayzah','Sekaka','Jizan','Al Qurrayyat',
'Al Bahah','Qalat Bishah','Ar Rass','Ash Shafa','Washington, D.C.','Phoenix','Austin','Columbus',
'Indianapolis','Denver','Boston','Nashville','Oklahoma City','Sacramento','Atlanta','Raleigh','Honolulu',
'Saint Paul','Lincoln','Madison','Baton Rouge','Richmond','Boise','Des Moines','Montgomery','Little Rock',
'Salt Lake City','Tallahassee','Providence','Jackson','Salem','Columbia','Topeka','Hartford','Moscow',
'Saint Petersburg','Novosibirsk','Yekaterinburg','Nizhniy Novgorod','Kazan','Samara','Omsk','Chelyabinsk',
'Rostov-na-Donu','Ufa','Krasnoyarsk','Perm','Volgograd','Voronezh','Saratov','Krasnodar','Izhevsk','Barnaul',
'Tyumen','Ulyanovsk','Irkutsk','Vladivostok','Yaroslavl','Khabarovsk','Makhachkala','Orenburg','London','Glasgow',
'Birmingham','Liverpool','Bristol','Sheffield','Manchester','Edinburgh','Leeds','Leicester','Bradford','Cardiff','Belfast','Aberdeen',]



